export enum HeroCode {
  Achilles = 'ACHL',
  Alice = 'ALIC',
  Leshen = 'LESH',
  Angel = 'ANGL',
  Annie = 'ANNI',
  Beowulf = 'BEOW',
  Bigfoot = 'FOOT',
  BlackPanther = 'PNTH',
  BlackWidow = 'WIDO',
  BloodyMary = 'MARY',
  BruceLee = 'BLEE',
  Buffy = 'BUFF',
  Bullseye = 'BULL',
  Ciri = 'CIRI',
  CloakDagger = 'CLOK',
  Daredevil = 'DARE',
  Deadpool = 'DEAD',
  DoctorStrange = 'STRG',
  JillTrent = 'JILL',
  Sattler = 'SATL',
  Dracula = 'DRAC',
  Elektra = 'ELEK',
  Eredin = 'ERED',
  Geralt = 'GRLT',
  GhostRider = 'GHST',
  GoldenBat = 'GBAT',
  Hamlet = 'HAML',
  Houdini = 'HOUD',
  InvisibleMan = 'INVS',
  JekyllHyde = 'JEKL',
  LittleRed = 'LRED',
  LukeCage = 'LUKE',
  Medusa = 'MEDU',
  MoonKnight = 'MOON',
  MsMarvel = 'MRVL',
  Tesla = 'TSLA',
  OdaNobunaga = 'NOBU',
  Philippa = 'PHIL',
  Raptors = 'RAPT',
  Muldoon = 'MULD',
  RobinHood = 'HOOD',
  Shakespeare = 'SHAK',
  SheHulk = 'HULK',
  Sherlock = 'SHER',
  Sinbad = 'SINB',
  Spike = 'SPIK',
  SpiderMan = 'SPID',
  SquirrelGirl = 'SQRL',
  SunWukong = 'WUKO',
  TRex = 'TREX',
  Genie = 'GENI',
  WaywardSisters = 'WAYW',
  Titania = 'TITA',
  TomoeGozen = 'TOMO',
  Willow = 'WILL',
  WinterSoldier = 'WINT',
  YenneferTriss = 'YENN',
  Yennenga = 'YENG',
  KingArthur = 'KGAR'
}

export const heroNames: Record<HeroCode, string> = {
  [HeroCode.Achilles]: 'Achilles',
  [HeroCode.Alice]: 'Alice',
  [HeroCode.Angel]: 'Angel',
  [HeroCode.Annie]: 'Annie Christmas',
  [HeroCode.Beowulf]: 'Beowulf',
  [HeroCode.BruceLee]: 'Bruce Lee',
  [HeroCode.Buffy]: 'Buffy',
  [HeroCode.Bullseye]: 'Bullseye',
  [HeroCode.Ciri]: 'Ciri',
  [HeroCode.CloakDagger]: 'Cloak Dagger',
  [HeroCode.Daredevil]: 'Daredevil',
  [HeroCode.Deadpool]: 'Deadpool',
  [HeroCode.Dracula]: 'Dracula',
  [HeroCode.Elektra]: 'Elektra',
  [HeroCode.Eredin]: 'Eredin',
  [HeroCode.Bigfoot]: 'Bigfoot',
  [HeroCode.GoldenBat]: 'Golden Bat',
  [HeroCode.Genie]: 'The Genie',
  [HeroCode.GhostRider]: 'Ghost Rider',
  [HeroCode.Geralt]: 'Geralt of Rivia',
  [HeroCode.Hamlet]: 'Hamlet',
  [HeroCode.RobinHood]: 'Robin Hood',
  [HeroCode.Houdini]: 'Harry Houdini',
  [HeroCode.SheHulk]: 'She Hulk',
  [HeroCode.InvisibleMan]: 'Invisible Man',
  [HeroCode.JekyllHyde]: 'Jekyll & Hyde',
  [HeroCode.JillTrent]: 'Dr. Jill Trent',
  [HeroCode.KingArthur]: 'King Arthur & Merlin',
  [HeroCode.Leshen]: 'Ancient Leshen',
  [HeroCode.LittleRed]: 'Little Red',
  [HeroCode.LukeCage]: 'Luke Cage',
  [HeroCode.BloodyMary]: 'Bloody Mary',
  [HeroCode.Medusa]: 'Medusa',
  [HeroCode.MoonKnight]: 'Moon Knight',
  [HeroCode.MsMarvel]: 'Ms. Marvel',
  [HeroCode.Muldoon]: 'Robert Muldoon',
  [HeroCode.OdaNobunaga]: 'Oda Nobunaga',
  [HeroCode.Philippa]: 'Philippa',
  [HeroCode.BlackPanther]: 'Black Panther',
  [HeroCode.Raptors]: 'Raptors',
  [HeroCode.Sattler]: 'Dr. Sattler',
  [HeroCode.Shakespeare]: 'Shakespeare',
  [HeroCode.Sherlock]: 'Sherlock Holmes',
  [HeroCode.Sinbad]: 'Sinbad',
  [HeroCode.SpiderMan]: 'Spiderman',
  [HeroCode.Spike]: 'Spike',
  [HeroCode.SquirrelGirl]: 'Squirrel Girl',
  [HeroCode.DoctorStrange]: 'Doctor Strange',
  [HeroCode.Titania]: 'Titania',
  [HeroCode.TomoeGozen]: 'Tomoe Gozen',
  [HeroCode.TRex]: 'T. Rex',
  [HeroCode.Tesla]: 'Nikola Tesla',
  [HeroCode.WaywardSisters]: 'The Wayward Sisters',
  [HeroCode.BlackWidow]: 'Black Widow',
  [HeroCode.Willow]: 'Willow',
  [HeroCode.WinterSoldier]: 'Winter Soldier',
  [HeroCode.SunWukong]: 'Sun Wukong',
  [HeroCode.Yennenga]: 'Yennenga',
  [HeroCode.YenneferTriss]: 'Yennefer & Triss'
}

export const heroImages: Record<HeroCode, string> = {
  [HeroCode.Achilles]: '/heroes/achilles.webp',
  [HeroCode.Alice]: '/heroes/alice.webp',
  [HeroCode.Angel]: '/heroes/angel.webp',
  [HeroCode.Annie]: '/heroes/annie.webp',
  [HeroCode.Beowulf]: '/heroes/beowulf.webp',
  [HeroCode.BruceLee]: '/heroes/bruce-lee.webp',
  [HeroCode.Buffy]: '/heroes/buffy.webp',
  [HeroCode.Bullseye]: '/heroes/bullseye.webp',
  [HeroCode.Ciri]: '/heroes/ciri.webp',
  [HeroCode.CloakDagger]: '/heroes/cloak-dagger.webp',
  [HeroCode.Daredevil]: '/heroes/daredevil.webp',
  [HeroCode.Deadpool]: '/heroes/deadpool.webp',
  [HeroCode.Dracula]: '/heroes/dracula.webp',
  [HeroCode.Elektra]: '/heroes/elektra.webp',
  [HeroCode.Eredin]: '/heroes/eredin.webp',
  [HeroCode.Bigfoot]: '/heroes/bigfoot.webp',
  [HeroCode.GoldenBat]: '/heroes/golden-bat.webp',
  [HeroCode.Genie]: '/heroes/genie.webp',
  [HeroCode.GhostRider]: '/heroes/ghost-rider.webp',
  [HeroCode.Geralt]: '/heroes/geralt.webp',
  [HeroCode.Hamlet]: '/heroes/hamlet.webp',
  [HeroCode.RobinHood]: '/heroes/robin-hood.webp',
  [HeroCode.Houdini]: '/heroes/houdini.webp',
  [HeroCode.SheHulk]: '/heroes/she-hulk.webp',
  [HeroCode.InvisibleMan]: '/heroes/invisible-man.webp',
  [HeroCode.JekyllHyde]: '/heroes/jekyll.webp',
  [HeroCode.JillTrent]: '/heroes/jill-trent.webp',
  [HeroCode.KingArthur]: '/heroes/arthur.webp',
  [HeroCode.Leshen]: '/heroes/leshen.webp',
  [HeroCode.LittleRed]: '/heroes/little-red.webp',
  [HeroCode.LukeCage]: '/heroes/luke-cage.webp',
  [HeroCode.BloodyMary]: '/heroes/bloody-mary.webp',
  [HeroCode.Medusa]: '/heroes/medusa.webp',
  [HeroCode.MoonKnight]: '/heroes/moon-knight.webp',
  [HeroCode.MsMarvel]: '/heroes/ms-marvel.webp',
  [HeroCode.Muldoon]: '/heroes/muldoon.webp',
  [HeroCode.OdaNobunaga]: '/heroes/nobunaga.webp',
  [HeroCode.Philippa]: '/heroes/philippa.webp',
  [HeroCode.BlackPanther]: '/heroes/black-panther.webp',
  [HeroCode.Raptors]: '/heroes/raptors.webp',
  [HeroCode.Sattler]: '/heroes/sattler.webp',
  [HeroCode.Shakespeare]: '/heroes/shakespeare.webp',
  [HeroCode.Sherlock]: '/heroes/sherlock.webp',
  [HeroCode.Sinbad]: '/heroes/sinbad.webp',
  [HeroCode.SpiderMan]: '/heroes/spiderman.webp',
  [HeroCode.Spike]: '/heroes/spike.webp',
  [HeroCode.SquirrelGirl]: '/heroes/squirrel-girl.webp',
  [HeroCode.DoctorStrange]: '/heroes/strange.webp',
  [HeroCode.Titania]: '/heroes/titania.webp',
  [HeroCode.TomoeGozen]: '/heroes/tomoe.webp',
  [HeroCode.TRex]: '/heroes/trex.webp',
  [HeroCode.Tesla]: '/heroes/tesla.webp',
  [HeroCode.WaywardSisters]: '/heroes/wayward-sisters.webp',
  [HeroCode.BlackWidow]: '/heroes/black-widow.webp',
  [HeroCode.Willow]: '/heroes/willow.webp',
  [HeroCode.WinterSoldier]: '/heroes/winter-soldier.webp',
  [HeroCode.SunWukong]: '/heroes/sun-wukong.webp',
  [HeroCode.Yennenga]: '/heroes/yennenga.webp',
  [HeroCode.YenneferTriss]: '/heroes/yennefer-triss.webp'
}


export enum MapCode {
  McMinnville = 'MCMV',
  PointPleasant = 'PLST',
  Marmoreal = 'MARM',
  Sarpedon = 'SARP',
  Baskerville = 'BASK',
  Soho = 'SOHO',
  Sunnydale = 'SUND',
  TheBronze = 'BRNZ',
  TheRaft = 'RAFT',
  SanctumSanctorum = 'SANC',
  NavyPier = 'NAVY',
  Helicarrier = 'HELI',
  HangingGardens = 'HANG',
  Novigrad = 'NOVI',
  GlobeTheatre = 'GLOB',
  KaerMorhen = 'KAER',
  Fayrlund = 'FAYR',
  HellKitchen = 'HELL',
  Yukon = 'YUKN',
  Sherwood = 'SHRW',
  KingSolomonsMine = 'SOLM',
  RaptorPaddock = 'RAPP',
  Heorot = 'HEOR',
  Azuchi = 'AZUC',
  Naglfar = 'NAGL',
  TrexPaddock = 'TREX'
}

export const mapNames: Record<MapCode, string> = {
  [MapCode.Azuchi]: 'Azuchi Castle',
  [MapCode.Baskerville]: 'Baskerville Manor',
  [MapCode.TheBronze]: 'The Bronze',
  [MapCode.Fayrlund]: 'Fayrlund Forest',
  [MapCode.GlobeTheatre]: 'Globe Theatre',
  [MapCode.HangingGardens]: 'Hanging Gardens',
  [MapCode.Helicarrier]: 'Helicarrier',
  [MapCode.HellKitchen]: "Hell's Kitchen",
  [MapCode.Heorot]: 'Heorot',
  [MapCode.KaerMorhen]: 'Kaer Morhen',
  [MapCode.Marmoreal]: 'Marmoreal',
  [MapCode.McMinnville]: 'McMinnville OR',
  [MapCode.Naglfar]: 'Naglfar',
  [MapCode.NavyPier]: 'Navy Pier',
  [MapCode.Novigrad]: 'Streets of Novigrad',
  [MapCode.PointPleasant]: 'Point Pleasant',
  [MapCode.TheRaft]: 'The Raft',
  [MapCode.RaptorPaddock]: 'Raptor Paddock',
  [MapCode.SanctumSanctorum]: 'Sanctum Sanctorum',
  [MapCode.Sarpedon]: 'Sarpedon',
  [MapCode.Sherwood]: 'Sherwood Forest',
  [MapCode.Soho]: 'Soho',
  [MapCode.KingSolomonsMine]: "King Solomon's Mine",
  [MapCode.Sunnydale]: 'Sunnydale High',
  [MapCode.TrexPaddock]: 'T. Rex Paddock',
  [MapCode.Yukon]: 'Yukon'
}

export const mapImages: Record<MapCode, string> = {
  [MapCode.Azuchi]: '/maps/azuchi.webp',
  [MapCode.Baskerville]: '/maps/baskerville.webp',
  [MapCode.TheBronze]: '/maps/bronze.webp',
  [MapCode.Fayrlund]: '/maps/fayrlund.webp',
  [MapCode.GlobeTheatre]: '/maps/globe.webp',
  [MapCode.HangingGardens]: '/maps/hanging-gardens.webp',
  [MapCode.Helicarrier]: '/maps/helicarrier.webp',
  [MapCode.HellKitchen]: '/maps/hells-kitchen.webp',
  [MapCode.Heorot]: '/maps/heorot.webp',
  [MapCode.KaerMorhen]: '/maps/kaer-morhen.webp',
  [MapCode.Marmoreal]: '/maps/marmoreal.webp',
  [MapCode.McMinnville]: '/maps/mcminnville.webp',
  [MapCode.Naglfar]: '/maps/naglfar.webp',
  [MapCode.NavyPier]: '/maps/navy-pier.webp',
  [MapCode.Novigrad]: '/maps/novigrad.webp',
  [MapCode.PointPleasant]: '/maps/point-pleasant.webp',
  [MapCode.TheRaft]: '/maps/raft.webp',
  [MapCode.RaptorPaddock]: '/maps/raptor.webp',
  [MapCode.SanctumSanctorum]: '/maps/sanctum.webp',
  [MapCode.Sarpedon]: '/maps/sarpedon.webp',
  [MapCode.Sherwood]: '/maps/sherwood.webp',
  [MapCode.Soho]: '/maps/soho.webp',
  [MapCode.KingSolomonsMine]: '/maps/solomons-mine.webp',
  [MapCode.Sunnydale]: '/maps/sunnydale.webp',
  [MapCode.TrexPaddock]: '/maps/trex.webp',
  [MapCode.Yukon]: '/maps/yukon.webp'
}
