export type HeroCode = 'ACHL' | 'ALIC' | 'LESH' | 'ANGL' | 'ANNI' | 'BEOW' | 'FOOT' | 'PNTH' |
  'WIDO' | 'MARY' | 'BLEE' | 'BUFF' | 'BULL' | 'CIRI' | 'CLOK' | 'DARE' | 'DEAD' | 'STRG' |
  'JILL' | 'SATL' | 'DRAC' | 'ELEK' | 'ERED' | 'GRLT' | 'GHST' | 'GBAT' | 'HAML' | 'HOUD' |
  'INVS' | 'JEKL' | 'LRED' | 'LUKE' | 'MEDU' | 'MOON' | 'MRVL' | 'TSLA' | 'NOBU' | 'PHIL' |
  'RAPT' | 'MULD' | 'HOOD' | 'SHAK' | 'HULK' | 'SHER' | 'SINB' | 'SPIK' | 'SPID' | 'SQRL' |
  'WUKO' | 'TREX' | 'GENI' | 'WAYW' | 'TITA' | 'TOMO' | 'WILL' | 'WINT' | 'YENN' | 'YENG' | 'KGAR'


export const heroNames: Record<HeroCode, string> = {
  'ACHL': 'Achilles',
  'ALIC': 'Alice',
  'ANGL': 'Angel',
  'ANNI': 'Annie Christmas',
  'BEOW': 'Beowulf',
  'BLEE': 'Bruce Lee',
  'BUFF': 'Buffy',
  'BULL': 'Bullseye',
  'CIRI': 'Ciri',
  'CLOK': 'Cloak Dagger',
  'DARE': 'Daredevil',
  'DEAD': 'Deadpool',
  'DRAC': 'Dracula',
  'ELEK': 'Elektra',
  'ERED': 'Eredin',
  'FOOT': 'Bigfoot',
  'GBAT': 'Golden Bat',
  'GENI': 'The Genie',
  'GHST': 'Ghost Rider',
  'GRLT': 'Geralt of Rivia',
  'HAML': 'Hamlet',
  'HOOD': 'Robin Hood',
  'HOUD': 'Harry Houdini',
  'HULK': 'She Hulk',
  'INVS': 'Invisible Man',
  'JEKL': 'Jekyll & Hyde',
  'JILL': 'Dr. Jill Trent',
  'KGAR': 'King Arthur & Merlin',
  'LESH': 'Ancient Leshen',
  'LRED': 'Little Red',
  'LUKE': 'Luke Cage',
  'MARY': 'Bloody Mary',
  'MEDU': 'Medusa',
  'MOON': 'Moon Knight',
  'MRVL': 'Ms. Marvel',
  'MULD': 'Robert Muldoon',
  'NOBU': 'Oda Nobunaga',
  'PHIL': 'Philippa',
  'PNTH': 'Black Panther',
  'RAPT': 'Raptors',
  'SATL': 'Dr. Sattler',
  'SHAK': 'Shakespeare',
  'SHER': 'Sherlock Holmes',
  'SINB': 'Sinbad',
  'SPID': 'Spiderman',
  'SPIK': 'Spike',
  'SQRL': 'Squirrel Girl',
  'STRG': 'Doctor Strange',
  'TITA': 'Titania',
  'TOMO': 'Tomoe Gozen',
  'TREX': 'T. Rex',
  'TSLA': 'Nikola Tesla',
  'WAYW': 'The Wayward Sisters',
  'WIDO': 'Black Widow',
  'WILL': 'Willow',
  'WINT': 'Winter Soldier',
  'WUKO': 'Sun Wukong',
  'YENG': 'Yennenga',
  'YENN': 'Yennefer & Triss'
}

export const heroImages: Record<HeroCode, string> = {
  'ACHL': '/heroes/achilles.webp',
  'ALIC': '/heroes/alice.webp',
  'ANGL': '/heroes/angel.webp',
  'ANNI': '/heroes/annie.webp',
  'BEOW': '/heroes/beowulf.webp',
  'BLEE': '/heroes/bruce-lee.webp',
  'BUFF': '/heroes/buffy.webp',
  'BULL': '/heroes/bullseye.webp',
  'CIRI': '/heroes/ciri.webp',
  'CLOK': '/heroes/cloak-dagger.webp',
  'DARE': '/heroes/daredevil.webp',
  'DEAD': '/heroes/deadpool.webp',
  'DRAC': '/heroes/dracula.webp',
  'ELEK': '/heroes/elektra.webp',
  'ERED': '/heroes/eredin.webp',
  'FOOT': '/heroes/bigfoot.webp',
  'GBAT': '/heroes/golden-bat.webp',
  'GENI': '/heroes/genie.webp',
  'GHST': '/heroes/ghost-rider.webp',
  'GRLT': '/heroes/geralt.webp',
  'HAML': '/heroes/hamlet.webp',
  'HOOD': '/heroes/robin-hood.webp',
  'HOUD': '/heroes/houdini.webp',
  'HULK': '/heroes/she-hulk.webp',
  'INVS': '/heroes/invisible-man.webp',
  'JEKL': '/heroes/jekyll.webp',
  'JILL': '/heroes/jill-trent.webp',
  'KGAR': '/heroes/arthur.webp',
  'LESH': '/heroes/leshen.webp',
  'LRED': '/heroes/little-red.webp',
  'LUKE': '/heroes/luke-cage.webp',
  'MARY': '/heroes/bloody-mary.webp',
  'MEDU': '/heroes/medusa.webp',
  'MOON': '/heroes/moon-knight.webp',
  'MRVL': '/heroes/ms-marvel.webp',
  'MULD': '/heroes/muldoon.webp',
  'NOBU': '/heroes/nobunaga.webp',
  'PHIL': '/heroes/philippa.webp',
  'PNTH': '/heroes/black-panther.webp',
  'RAPT': '/heroes/raptors.webp',
  'SATL': '/heroes/sattler.webp',
  'SHAK': '/heroes/shakespeare.webp',
  'SHER': '/heroes/sherlock.webp',
  'SINB': '/heroes/sinbad.webp',
  'SPID': '/heroes/spiderman.webp',
  'SPIK': '/heroes/spike.webp',
  'SQRL': '/heroes/squirrel-girl.webp',
  'STRG': '/heroes/strange.webp',
  'TITA': '/heroes/titania.webp',
  'TOMO': '/heroes/tomoe.webp',
  'TREX': '/heroes/trex.webp',
  'TSLA': '/heroes/tesla.webp',
  'WAYW': '/heroes/wayward-sisters.webp',
  'WIDO': '/heroes/black-widow.webp',
  'WILL': '/heroes/willow.webp',
  'WINT': '/heroes/winter-soldier.webp',
  'WUKO': '/heroes/sun-wukong.webp',
  'YENG': '/heroes/yennenga.webp',
  'YENN': '/heroes/yennefer-triss.webp'
}


export type MapCode = 'MCMV' | 'PLST' | 'MARM' | 'SARP' | 'BASK' | 'SOHO' | 'SUND' |
  'BRNZ' | 'RAFT' | 'SANC' | 'NAVY' | 'HELI' | 'HANG' | 'NOVI' | 'GLOB' | 'KAER' | 'FAYR' |
  'HELL' | 'YUKN' | 'SHRW' | 'SOLM' | 'RAPP' | 'HEOR' | 'AZUC' | 'NAGL' | 'TREX';

export const mapNames: Record<MapCode, string> = {
  'AZUC': 'Azuchi Castle',
  'BASK': 'Baskerville Manor',
  'BRNZ': 'The Bronze',
  'FAYR': 'Fayrlund Forest',
  'GLOB': 'Globe Theatre',
  'HANG': 'Hanging Gardens',
  'HELI': 'Helicarrier',
  'HELL': "Hell's Kitchen",
  'HEOR': 'Heorot',
  'KAER': 'Kaer Morhen',
  'MARM': 'Marmoreal',
  'MCMV': 'McMinnville OR',
  'NAGL': 'Naglfar',
  'NAVY': 'Navy Pier',
  'NOVI': 'Streets of Novigrad',
  'PLST': 'Point Pleasant',
  'RAFT': 'The Raft',
  'RAPP': 'Raptor Paddock',
  'SANC': 'Sanctum Sanctorum',
  'SARP': 'Sarpedon',
  'SHRW': 'Sherwood Forest',
  'SOHO': 'Soho',
  'SOLM': "King Solomon's Mine",
  'SUND': 'Sunnydale High',
  'TREX': 'T. Rex Paddock',
  'YUKN': 'Yukon'
}

export const mapImages: Record<MapCode, string> = {
  'AZUC': '/maps/azuchi.webp',
  'BASK': '/maps/baskerville.webp',
  'BRNZ': '/maps/bronze.webp',
  'FAYR': '/maps/fayrlund.webp',
  'GLOB': '/maps/globe.webp',
  'HANG': '/maps/hanging-gardens.webp',
  'HELI': '/maps/helicarrier.webp',
  'HELL': '/maps/hells-kitchen.webp',
  'HEOR': '/maps/heorot.webp',
  'KAER': '/maps/kaer-morhen.webp',
  'MARM': '/maps/marmoreal.webp',
  'MCMV': '/maps/mcminnville.webp',
  'NAGL': '/maps/naglfar.webp',
  'NAVY': '/maps/navy-pier.webp',
  'NOVI': '/maps/novigrad.webp',
  'PLST': '/maps/point-pleasant.webp',
  'RAFT': '/maps/raft.webp',
  'RAPP': '/maps/raptor.webp',
  'SANC': '/maps/sanctum.webp',
  'SARP': '/maps/sarpedon.webp',
  'SHRW': '/maps/sherwood.webp',
  'SOHO': '/maps/soho.webp',
  'SOLM': '/maps/solomons-mine.webp',
  'SUND': '/maps/sunnydale.webp',
  'TREX': '/maps/trex.webp',
  'YUKN': '/maps/yukon.webp'
}
