export const heroes = {
  "Hell's Kitchen": ['Daredevil', 'Bullseye', 'Elektra'],
  'For King and Country': ['Winter Soldier', 'Black Widow', 'Black Panther'],
  "Sun's Origin": ['Oda Nobunaga', 'Tomoe Gozen'],
  'Battle of Legends, Volume One': ['Sinbad', 'King Arthur', 'Medusa', 'Alice'],
  'Buffy the Vampire Slayer': ['Willow', 'Buffy', 'Angel', 'Spike'],
  'Redemption Row': ['Luke Cage', 'Moon Knight', 'Ghost Rider'],
  'Houdini vs. The Genie': ['Harry Houdini', 'The Genie'],
  'Cobble & Fog': ['Sherlock Holmes', 'Jekyll & Hyde', 'Invisible Man', 'Dracula'],
  'Brains and Brawn': ['Spiderman', 'Doctor Strange', 'She Hulk'],
  'Bruce Lee': ['Bruce Lee'],
  'Adventures - Tales to Amaze': [
    'Golden Bat',
    'Annie Christmas',
    'Dr. Jill Trent',
    'Nikola Tesla',
  ],
  'Robin Hood vs Bigfoot': ['Robin Hood', 'Bigfoot'],
  'Battle of Legends, Volume Two': ['Sun Wukong', 'Bloody Mary', 'Achilles', 'Yennenga'],
  'Teen Spirit': ['Cloak Dagger', 'Squirrel Girl', 'Ms. Marvel'],
  'Little Red Riding Hood vs. Beowulf': ['Little Red', 'Beowulf'],
  'Jurassic Park - Ingen vs. Raptors': ['Robert Muldoon', 'Raptors'],
  Deadpool: ['Deadpool'],
  'Jurassic Park - Sattler vs. T-Rex': ['Dr. Sattler', 'T. Rex'],
  'Slings and Arrows': ['The Wayward Sisters', 'Shakespeare', 'Titania', 'Hamlet'],
}

export const maps = {
  'Adventures - Tales to Amaze': ['McMinnville OR', 'Point Pleasant'],
  'Battle of Legends, Volume One': ['Marmoreal', 'Sarpedon'],
  'Cobble & Fog': ['Baskerville Manor', 'Soho'],
  'Buffy the Vampire Slayer': ['Sunnydale High', 'The Bronze'],
  'Redemption Row': ['The Raft'],
  'Brains and Brawn': ['Sanctum Sanctorum'],
  'Teen Spirit': ['Navy Pier'],
  'For King and Country': ['Helicarrier'],
  'Battle of Legends, Volume Two': ['Hanging Gardens'],
  'The Witcher - Realms Fall': ['Streets of Novigrad', 'Naglfar'],
  'Slings and Arrows': ['Globe Theatre'],
  'The Witcher - Steel & Silver': ['Kaer Morhen', 'Fayrlund Forest'],
  "Hell's Kitchen": ["Hell's Kitchen"],
  'Robin Hood vs Bigfoot': ['Yukon', 'Sherwood Forest'],
  'Houdini vs. The Genie': ["King Solomon's Mine"],
  'Jurassic Park - Ingen vs. Raptors': ['Raptor Paddock'],
  'Little Red Riding Hood vs. Beowulf': ['Heorot'],
  "Sun's Origin": ['Azuchi Castle'],
  'Jurassic Park - Sattler vs. T-Rex': ['T. Rex Paddock'],
}
